### ISSUE TITLE
Include RTS control for halfduplex RS485

### ISSUE THREAD

**Issue by christof1977** [nmakel/sdm_modbus#10]
Hi there,

I'm using a MAX485 transceiver chip, which provides halfduplex RS485 commnication. I modfied your code to set up the serial interface in a way to control the RTS pin. I'm testing it recently with 1.2 kbaud. Would it be an option to have it in your code or do you think it's too special?

Cheers
Christof

btw: thanks for your work, it seems to help me a lot!

**Comment by nmakel** [comment]
Thanks for sharing, Christof. As you say it's not really a change that should be included by default. This issue is hopefully enough for those using a MAX485 TTL to Modbus converter to get their setup to work.
