### ISSUE TITLE
no answer using USR-TCP232-304

### ISSUE THREAD

**Issue by dr-insaner** [nmakel/sdm_modbus#12]
Dear Nils,

I`m working on my photovoltaics home project. I´m able to read my three Eastron power meters. Two are at two different photovoltaics converters one is at power grid. I´m able to switch electricity consumers when producing too much power.
The power meters are connected to a rs485 <-> ethernet transmitter https://usriot.ru/download/M0/USR-TCP232-304-User%20Manual-V1.1.pdf

working code with USR-TCP232-304 using UDP server looks like:
--------------------------------------

import socket, time, datetime, platform, os
import struct

#PV-klein
SPANNUNG_PV = bytes.fromhex('01040000000271cb') #Spannung V
BAUDRATE_PV = bytes.fromhex('0103001C001C85C5') #Baudrate'
BAUDRATE_SET = bytes.fromhex('0116001C0002040002000232E8') #Baudrate'

WARTEN_AUF_ANTWORT_SEKUNDEN = 3

INTERVAL_SECS = 3

def _WertParsen(antwort):
  return round(float(struct.unpack('f', bytes(reversed(antwort[3:7])))[0]),2)

class StromZaehler:
    def __init__(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.settimeout(WARTEN_AUF_ANTWORT_SEKUNDEN)

    def HoleWert(self, anfrage):
        while True:
            try:
                self.sock.sendto(anfrage, ("192.168.2.108", 5111))
                antwort = self.sock.recv(4096)
                print(antwort)
                print(50*'-')
                return _WertParsen(antwort)
            except socket.timeout as e:
                print("Timeout, versuche es wieder ...", e)
                time.sleep(1)
            except socket.error as e:
                # Something else happened, handle error, exit, etc.
                print("Anderer Socket Fehler:", e)
                time.sleep(5)

    def update(self):
        try:
            #self.dec_spannung_pv = self.HoleWert(SPANNUNG_PV)
            self.dec_baudrate_pv = self.HoleWert(BAUDRATE_PV)
            #self.dec_baudrate_set = self.HoleWert(BAUDRATE_SET)

        except Exception as e:
            print("Fehler beim Strom Daten holen", e)

if __name__ == "__main__":

    stromz = StromZaehler()
    while True:
      try:
        stromz.update()
        print('PV1')
        #print(stromz.dec_spannung_pv, 'V')
        print(stromz.dec_baudrate_pv, 'baud')
        #print(stromz.dec_baudrate_set, 'baud')

      except Exception as e:
          print("Fehler beim verarbeiten", e)

      time.sleep(INTERVAL_SECS)

-------------------------------------------------
But I never managed to change the baudrate. I tried this using your code.
But I unfortunately don´t receive an answer from my power meters.
Code looks like:
#!/usr/bin/env python3

import argparse
import json
import sdm_modbus

if __name__ == "__main__":

    device_1 = sdm_modbus.SDM230(host="192.168.2.108", port=5111, unit=1)
    print(device_1.connected())

    device_1.read("voltage")

---------------------------
The USR seems to reive date from the script, but the eastrons are not answering.
Can you think of a reason?

Thanks a lot for your help!

Best regards,

Jan

![image](https://user-images.githubusercontent.com/71705065/147705991-c1e5618b-a19a-4900-8b88-c708a9906cf7.png)

![image](https://user-images.githubusercontent.com/71705065/147706015-8d311ff1-9c72-4c1d-bb6d-d454d9dc29a8.png)

**Comment by nmakel** [comment]
> But I never managed to change the baudrate. I tried this using your code. But I unfortunately don´t receive an answer from my power meters. Code looks like: #!/usr/bin/env python3

Does your own code to set the baud rate work? Does reading registers work? Have you put the Eastron modules into the required mode to alter the baud rate?

> The USR seems to reive date from the script, but the eastrons are not answering. Can you think of a reason?

This might be a framing issue, but to know more you should run the `sdm_modbus` library with debug logging on. You should be able to get debug output from pymobus by adding this to your script:

```
import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
```
