### ISSUE TITLE
Strange Registers read in SDM630

### ISSUE THREAD

**Issue by SebuZet** [nmakel/sdm_modbus#13]
Hi,

It looks like there is some strange code. Please take a look at line 262:

            "l1_demand_energy_active": (0x015a, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L1 Import Energy (Active)", "kWh", 4, 1),
            "l2_demand_energy_active": (0x015c, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L2 Import Energy (Active)", "kWh", 4, 1),
            "l3_demand_energy_active": (0x015e, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L3 Import Energy (Active)", "kWh", 4, 1),
            "l1_import_energy_active": (0x0160, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L1 Import Energy (Active)", "kWh", 4, 1),
            "l2_import_energy_active": (0x0162, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L2 Import Energy (Active)", "kWh", 4, 1),
            "l3_import_energy_active": (0x0164, 2, meter.registerType.INPUT, meter.registerDataType.FLOAT32, float, "L3 Import Energy (Active)", "kWh", 4, 1),

Those registers are:
SDM_L1_IMPORT_ACTIVE_ENERGY = 0x015A;
SDM_L2_IMPORT_ACTIVE_ENERGY = 0x015C;
SDM_L3_IMPORT_ACTIVE_ENERGY = 0x015E;
SDM_L1_EXPORT_ACTIVE_ENERGY = 0x0160;
SDM_L2_EXPORT_ACTIVE_ENERGY = 0x0162;
SDM_L3_EXPORT_ACTIVE_ENERGY = 0x0164;

Is it intensional?

**Comment by nmakel** [comment]
You're absolutely right. Check the latest commit, this should reflect the correct registers.
