### ISSUE TITLE
connected() returns False

### ISSUE THREAD

**Issue by radokristof** [nmakel/sdm_modbus#16]
Instanciating a new device and checking connected() will return False.

It will be only True, if I execute something before reading this.

**Comment by nmakel** [comment]
I've added `self.connect()` to the end of the meter init function. This will result in the expected and documented behavior.

**Comment by radokristof** [comment]
Thanks, will test it soon!

**Comment by radokristof** [comment]
@nmakel Maybe can you release a new patch version on pypi which includes these fixes? Thanks!
