### ISSUE TITLE
What is the minimum values needed for a proxy meter to work?

### ISSUE THREAD

**Issue by magpern** [nmakel/sdm_modbus#5]
I have a Victron battery system externally connected to my house's grid and on this grid there is a SolarEdge PV inverter.

I have a working smart meter connected to the SolarEdge (Inepro Pro380) so it knows what goes in and out from the grid connection point,

However, the victron system charges the battery as soon as there is an excess f energy flowing from the house. This is reported in the SolarEdge app as consumption (blue).
When there is no excess power, the victron start supplying the house with battery power.
The SolarEdge cannot see this electricity, and registeres nothing. In the app, there is nothing when the battery is discharging.

But, the victron system know the "AC Loads" being drawn from the house.
And the victron system is Modbus TCP enabled. You can get most things out of the system over Modbus TCP.

So I was thinking to modify your code and make a "Victron system adapter", that way I could have sdm_modbus read the comsumption/AC loads and report this as a consumption meter to SolarEdge.

What is the minimum data needed from a source for the driver/proxy to work as a solaredge meter. I don't have all values, like reactive power, voltage etc. I have the number of watts used by each phase.

Voltage and current frequency can perhaps be gathered from an other modbus unit id in the victron system

[CCGX-Modbus-TCP-register-list-2.60.xlsx](https://github.com/nmakel/sdm_modbus/files/6098112/CCGX-Modbus-TCP-register-list-2.60.xlsx)

**Comment by nmakel** [comment]
Interesting question!

My first thought is that it might be more useful to expand on [solaredge_meterproxy](https://github.com/nmakel/solaredge_meterproxy) and make the Victron pretend it's an LG battery and not just a import+export meter.

As to your actual question, I'm not entirely sure at what point the SolarEdge is 'happy' with the data it is provided. I have a SDM120 connected to a SolarEdge inverter using the aforementioned solaredge_meterproxy and the number of datapoints it provides isn't huge. Looking at the register list you provided it should be more than adequate, provided they actually contain data.

**Comment by magpern** [comment]
Most data is available in the Modbus TCP registers in the venusos system, but they are on different UNIT ids. Like consumption is on UNIT 100 (system) and voltage and current is on UNIT is 227 (vebus)
Any thought on that?

As to the LG battery... that would be the best thing, but I have no idea how to "simulate a LG battery" not how to set it up in SetApp. My inverter is not battery ready, so I don't think the option to select a battery is there (SE17K).

**Comment by nmakel** [comment]
> Most data is available in the Modbus TCP registers in the venusos system, but they are on different UNIT ids. Like consumption is on UNIT 100 (system) and voltage and current is on UNIT is 227 (vebus)
> Any thought on that?

That shouldn't be a problem. The nature of modbus is that once you have a working physical connection addressing various IDs on the bus is trivial. `sdm_modbus` currently assumes you're talking to a single device with a single address, but that's a minor modification.

> As to the LG battery... that would be the best thing, but I have no idea how to "simulate a LG battery" nor how to set it up in SetApp. My inverter is not battery ready, so I don't think the option to select a battery is there (SE17K).

If you have SetApp you can check out the `Site Communication` page, then `RS485-1`, which should be set to multi-device already, and choose `Add Modbus Device`. There you'll have the option of adding another meter or battery device.

How this equates to SolarEdge's StorEdge product, and how the information gathered from the battery is used to fill in the blanks you have now, I have no clue. But it will be fun to find out :)

**Comment by magpern** [comment]
> 
> That shouldn't be a problem. The nature of modbus is that once you have a working physical connection addressing various IDs on the bus is trivial. `sdm_modbus` currently assumes you're talking to a single device with a single address, but that's a minor modification.
> 

My python coding skills is extremely limited (.NET guy). To make you proxy program able to read multiple unit ids and join then together into one payload that could be proxied as a SolarEdge smart meter - would be like learning to fly

> 
> If you have SetApp you can check out the `Site Communication` page, then `RS485-1`, which should be set to multi-device already, and choose `Add Modbus Device`. There you'll have the option of adding another meter or battery device.
> 

I checked. Under the "Add Modbus Device" the only option is "Meter". My inverter in the SolarEdge SE17K, and it is not a hybrid one, so I guess making it think it has a battery is limited in the firmware.

**Comment by nmakel** [comment]
> My python coding skills is extremely limited (.NET guy). To make you proxy program able to read multiple unit ids and join then together into one payload that could be proxied as a SolarEdge smart meter - would be like learning to fly

In that case you might be better off writing a quick .NET modbus client to grab the data from the Victron and dump it into a database. Retrieving the data from the database and feeding it to your inverter using solaredge_meterproxy is then possible.

> I checked. Under the "Add Modbus Device" the only option is "Meter". My inverter in the SolarEdge SE17K, and it is not a hybrid one, so I guess making it think it has a battery is limited in the firmware.

Ah too bad. In that case putting a second three phase kWh meter on the battery connection might just solve your problem with the least amount of fuss.

**Comment by magpern** [comment]
> 
> Ah too bad. Putting a second three phase kWh meter on the battery connection might just solve your problem with the least amount of fuss.

I installed a second physical meter yesterday, configured it as a consumption meter. Easiest way to go.
