### ISSUE TITLE
SDM72 provides more registers than stated in datasheet

### ISSUE THREAD

**Issue by christof1977** [nmakel/sdm_modbus#9]
Hi,

I just figured out, that the SDM72 provides more registers than stated in the datasheet. Would it be ok to add them? I can include and test them. Can I just push to your repo?

Cheer
Christof

**Comment by christof1977** [comment]
Ok, sounds good. However, I will need some time for doing so.

**Comment by nmakel** [comment]
SDM72 registers have been updated.
